### ISSUE TITLE
Timed Desktop Push Notification in To-Do Page

### ISSUE THREAD

**Issue by Erick-Bravo** [Erick-Bravo/tech_helper#1]
On the To-DO page, add a switch that can go back and forward between the To-Do component and the Timed Push Reminder component. 

- [ ]  Use Tabs, from Chakra UI
- [ ]  Switches between To-Do and Timed Reminder components
- [ ]  Can create the Reminder with a form
- [ ]  Form has "Reminder" and "Time"
- [ ] Time pushes desktop notification
